/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    events: Event;
    channels: Channel;
    'event-assignments': EventAssignment;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    channels: ChannelsSelect<false> | ChannelsSelect<true>;
    'event-assignments': EventAssignmentsSelect<false> | EventAssignmentsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'super_admin' | 'admin' | 'moderator';
  active?: boolean | null;
  preferredLanguage?: string | null;
  lastLogin?: string | null;
  invitationStatus?: ('none' | 'pending' | 'accepted' | 'expired') | null;
  invitedAt?: string | null;
  invitationAcceptedAt?: string | null;
  invitedBy?: (number | null) | User;
  /**
   * Reserved for a future 2FA flow.
   */
  twoFactorEnabled?: boolean | null;
  /**
   * Reserved for future 2FA method selection.
   */
  twoFactorMethod?: ('app' | 'email') | null;
  /**
   * Reserved for an encrypted future 2FA secret. Do not populate until encryption is implemented.
   */
  twoFactorSecret?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  status?: ('draft' | 'active' | 'archived') | null;
  eventLogo?: (number | null) | Media;
  dateStart?: string | null;
  dateEnd?: string | null;
  location?: string | null;
  defaultLanguage?: string | null;
  publicListenerEnabled?: boolean | null;
  listenerPasswordEnabled?: boolean | null;
  listenerPasswordHash?: string | null;
  speakerPasswordEnabled?: boolean | null;
  /**
   * Enter a new event-level speaker password. Only a secure hash is stored.
   */
  speakerPassword?: string | null;
  speakerPasswordHash?: string | null;
  /**
   * Derived from event assignments.
   */
  assignedAdmins?: (number | User)[] | null;
  /**
   * Derived from event assignments.
   */
  assignedModerators?: (number | User)[] | null;
  /**
   * Automatically synchronized from the Channels collection.
   */
  channels?: (number | Channel)[] | null;
  qrSettings?: {
    foregroundColor?: string | null;
    backgroundColor?: string | null;
    includeBlueAccent?: boolean | null;
  };
  themeOverride?: {
    enabled?: boolean | null;
    greenDark?: string | null;
    green?: string | null;
    greenLight?: string | null;
    blue?: string | null;
    blueDark?: string | null;
    background?: string | null;
    card?: string | null;
    text?: string | null;
  };
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channels".
 */
export interface Channel {
  id: number;
  event: number | Event;
  name: string;
  slug: string;
  languageCode?: string | null;
  languageLabel?: string | null;
  description?: string | null;
  enabled?: boolean | null;
  sortOrder?: number | null;
  /**
   * Compatibility room name if older clients depend on it.
   */
  roomName?: string | null;
  /**
   * Server-side LiveKit room name.
   */
  livekitRoomName?: string | null;
  webrtcEnabled?: boolean | null;
  hlsEnabled?: boolean | null;
  icecastFallbackUrl?: string | null;
  listenerPageEnabled?: boolean | null;
  speakerPageEnabled?: boolean | null;
  listenerTokenMode?: ('public' | 'password' | 'private') | null;
  speakerPasswordEnabled?: boolean | null;
  /**
   * Enter a new channel-level speaker password. Only a secure hash is stored.
   */
  speakerPassword?: string | null;
  speakerPasswordHash?: string | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-assignments".
 */
export interface EventAssignment {
  id: number;
  user: number | User;
  event: number | Event;
  roleForEvent: 'admin' | 'moderator' | 'viewer';
  permissions?: {
    canEditEvent?: boolean | null;
    canCreateChannels?: boolean | null;
    canDeleteChannels?: boolean | null;
    canViewQR?: boolean | null;
    canManageSpeakerPassword?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  user?: (number | null) | User;
  action: string;
  collection?: string | null;
  documentId?: string | null;
  event?: (number | null) | Event;
  channel?: (number | null) | Channel;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'channels';
        value: number | Channel;
      } | null)
    | ({
        relationTo: 'event-assignments';
        value: number | EventAssignment;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  preferredLanguage?: T;
  lastLogin?: T;
  invitationStatus?: T;
  invitedAt?: T;
  invitationAcceptedAt?: T;
  invitedBy?: T;
  twoFactorEnabled?: T;
  twoFactorMethod?: T;
  twoFactorSecret?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  status?: T;
  eventLogo?: T;
  dateStart?: T;
  dateEnd?: T;
  location?: T;
  defaultLanguage?: T;
  publicListenerEnabled?: T;
  listenerPasswordEnabled?: T;
  listenerPasswordHash?: T;
  speakerPasswordEnabled?: T;
  speakerPassword?: T;
  speakerPasswordHash?: T;
  assignedAdmins?: T;
  assignedModerators?: T;
  channels?: T;
  qrSettings?:
    | T
    | {
        foregroundColor?: T;
        backgroundColor?: T;
        includeBlueAccent?: T;
      };
  themeOverride?:
    | T
    | {
        enabled?: T;
        greenDark?: T;
        green?: T;
        greenLight?: T;
        blue?: T;
        blueDark?: T;
        background?: T;
        card?: T;
        text?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channels_select".
 */
export interface ChannelsSelect<T extends boolean = true> {
  event?: T;
  name?: T;
  slug?: T;
  languageCode?: T;
  languageLabel?: T;
  description?: T;
  enabled?: T;
  sortOrder?: T;
  roomName?: T;
  livekitRoomName?: T;
  webrtcEnabled?: T;
  hlsEnabled?: T;
  icecastFallbackUrl?: T;
  listenerPageEnabled?: T;
  speakerPageEnabled?: T;
  listenerTokenMode?: T;
  speakerPasswordEnabled?: T;
  speakerPassword?: T;
  speakerPasswordHash?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-assignments_select".
 */
export interface EventAssignmentsSelect<T extends boolean = true> {
  user?: T;
  event?: T;
  roleForEvent?: T;
  permissions?:
    | T
    | {
        canEditEvent?: T;
        canCreateChannels?: T;
        canDeleteChannels?: T;
        canViewQR?: T;
        canManageSpeakerPassword?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  collection?: T;
  documentId?: T;
  event?: T;
  channel?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  defaultLogo?: (number | null) | Media;
  publicBaseUrl?: string | null;
  supportEmail?: string | null;
  allowPublicListenerPages?: boolean | null;
  requireEmailVerification?: boolean | null;
  defaultTokenExpiry?: number | null;
  livekitPublicUrl?: string | null;
  defaultQrStyle?: ('undersound-default' | 'high-contrast') | null;
  defaultThemeColors?: {
    greenDark?: string | null;
    green?: string | null;
    greenLight?: string | null;
    blue?: string | null;
    blueDark?: string | null;
    background?: string | null;
    card?: string | null;
    text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  defaultLogo?: T;
  publicBaseUrl?: T;
  supportEmail?: T;
  allowPublicListenerPages?: T;
  requireEmailVerification?: T;
  defaultTokenExpiry?: T;
  livekitPublicUrl?: T;
  defaultQrStyle?: T;
  defaultThemeColors?:
    | T
    | {
        greenDark?: T;
        green?: T;
        greenLight?: T;
        blue?: T;
        blueDark?: T;
        background?: T;
        card?: T;
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}